apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  storageClassName: standard
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-deployment
  template:
    metadata:
      labels:
        app: tasks-deployment
    spec:
      volumes:
        - name: tasks-volume
          persistentVolumeClaim:
            claimName: host-pvc
      containers:
        - name: tasks-container
          image: rijojohn85/kub-demo-tasks:latest
          volumeMounts:
            - mountPath: /app/tasks
              name: tasks-volume
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: "tasks"
